#!/bin/bash

## Description: Run magerun in Magento 2.4
## Usage: mr2-dev-24 <options> <arguments>
## Example: "mr2-dev-24 sys:info"

bin/n98-magerun2 --root-dir=/opt/magento-test-environments/magento_2_4_3_p1 $@
