#!/bin/bash

## Description: Run magerun in Magento 2.3
## Usage: mr2-dev-23 <options> <arguments>
## Example: "mr2-dev-23 sys:info"

bin/n98-magerun2 --root-dir=/opt/magento-test-environments/magento_2_3_7_p2 $@
