#!/bin/bash

## Description: Run n98-magerun2 code checks
## Usage: qa
## Example: "qa"

PROJECT_DIR="/var/www/html";

echo "---------------------------------------------------------";
echo "RUN php-cs-fixer"
echo "---------------------------------------------------------";

vendor/bin/php-cs-fixer fix --verbose --dry-run --diff;

echo "---------------------------------------------------------";
echo "RUN phpstan"
echo "---------------------------------------------------------";

if [ -z "$MAGERUN_SETUP_TEST_DEFAULT_MAGENTO_VERSION" ]; then
		echo "Please add MAGERUN_SETUP_TEST_DEFAULT_MAGENTO_VERSION as web_environment variable in your .ddev/config.yaml."
		echo "See: https://github.com/netz98/n98-magerun2/blob/develop/.ddev/config.yaml"
		exit 1;
fi

MAGENTO_ROOT_DIR="/opt/magento-test-environments/magento_${MAGERUN_SETUP_TEST_DEFAULT_MAGENTO_VERSION//[-.]/_}"
cd "$MAGENTO_ROOT_DIR";
/var/www/html/vendor/bin/phpstan analyze -a "$PROJECT_DIR/src/bootstrap.php" "$PROJECT_DIR/src";
